name: main

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: make test
    - run: make clean
