name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Env setup
      run: |
        sudo apt update
        sudo apt install valgrind
    - name: Build
      run: make
    - name: Test
      run: make test
    - name: Memory check
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all \
          --quiet --error-exitcode=1 ./halloc_test
